# Generated by Django 3.0.6 on 2020-06-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='state',
        ),
    ]
